spring.application.name=be

#JWT
jwt.secret=heavenshop2024
jwt.expiration=604800000

#My SQL
spring.datasource.url=jdbc:mysql://localhost:3306/heavenshop
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hi?n th? query SQL
spring.jpa.show-sql=true

# Format query d? ??c h?n
spring.jpa.properties.hibernate.format_sql=true

# Ghi log query ? m?c DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Hi?n th? các tham s? ???c truy?n vào query
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

